#!/bin/bash

# Pull in the variables from the external file. This should define $FORM_VALUES.
source "$(dirname "$0")/uw-ethics-vars"

# Get the CSS file first
CSS=`which gdoc2pdf | sed 's/bin\/gdoc2pdf/lib\/node_modules\/gdoc2pdf\/src\/styles\/no-h3-no-highlights\.css/'`

CONSENT='https://docs.google.com/document/d/1EffPq6GcAEmVJo29hvets215AY3NDxFcM8OahDiTwjk/edit'
gdoc2pdf -f $CONSENT -v $FORM_VALUES -o consent.pdf -c $CSS
