#!/bin/bash

# Project name to identify output folder. 
# Eg. 'ControllerBlocksSession1', 'coediting', something identifiable if you have multiple projects that need ethics amendments.
# Leave as '' if no name necessary.
PROJECT_NAME=''

# Should be a copy of https://docs.google.com/document/d/1y4Gjx9cKh3-iXG3HsPghtEVKo4BujKWM166d1CoLIlw/edit
FORM_VALUES='https://docs.google.com/document/d/1YCPN67yHKevrIcvQLTb39E5k2_F_zC0icoI3bVyY0-I/edit'

# Should be a copy of https://docs.google.com/document/d/1R0_xQvjYrq384j0ur_1CNCEQvOPBQTCxM4Gq_XWd4iY/edit
METHOD='https://docs.google.com/document/d/1jrmnzAUV1px01-xGAHDtVcnj5x-cCq4jYwUOumZJIZc/edit'

# Should be the appropriate template for your specific type of study.
# Below is the template for surveys.
TEMPLATE='https://docs.google.com/document/d/1C_hEbezrXjH61pkuU-aScdbujMagSlw1PU7B8kKybyI/edit'

# If you have additional files (questionnaires, etc) to append to the generated PDF, specify the full path to the file here.
# If multiple files, specify the full path to the directory containing the files you want to append.
# Only works for PDF files!
# Example: "/Users/johannwentzel/Desktop/PDF Files" or "/Users/johannwentzel/Desktop/pre-questionnaire.pdf".
ADDITIONAL_FILES="CHANGEME"
